name: run_dbCAN_new
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyrodigal
  - pyhmmer
  - diamond
  - pandas
  - bcbio-gff
  - tqdm
  - requests
  - openpyxl
  - matplotlib
  - biopython=1.84
  - pysam
  - seaborn
  - pip
  - pip:
    - run-dbcan-new
